#
# Containers de desenvolvimento Incentive.me
#
version: '3.5'

networks:
  quiosque-network:
    name: quiosque-network

services:
  mysql-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
    networks:
      - quiosque-network
